# Generated by Django 5.0.6 on 2024-05-27 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre de la tarea')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción de la tarea')),
                ('state', models.CharField(choices=[('TO DO', 'To do'), ('DOING', 'Doing'), ('DONE', 'Done'), ('BACKLOG', 'Backlog'), ('USER TEST', 'User test'), ('TESTING', 'Testing')], max_length=30, verbose_name='Estado de la tarea')),
                ('date', models.DateField(verbose_name='Fecha de la tarea')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Dueño de la tarea')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['date'],
            },
        ),
    ]
