# Generated by Django 5.0.6 on 2024-06-21 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkStream', '0002_alter_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='assigned_users',
        ),
    ]
