# Generated by Django 5.0.6 on 2024-06-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkStream', '0004_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(),
        ),
    ]
